laravel_ducnn/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/users', 'UserController');

Auth::Routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

laravel_ducnn/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style type="text/css">
        span {
            color: red ;
        }
        #menu ul {
            list-style-type: none;
        }
        #menu li {
            color: #f1f1f1;
            display: inline-block;
            width: 150px;
            height: 40px;
            line-height: 20px;
            margin : 0px;
        }
        #menu ul {
            list-style-type: none;
            overflow: hidden;
            width: 100%;
        }
        #menu a {
            text-decoration: none;
            display: block;
        }
        #menu a:hover {
            background: white;
            color: black;
        }
        footer {
            background : black;
            color : white;
            text-align : center;
            height : 60px;
        }
        h2 {
            padding-top : 15px;
        }
        body{
            padding: 5px;
        }
    </style> 
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @include('layouts.header')
        <main class="py-4">
            @yield('content')
        </main>
        @include('layouts.footer')
    </div>
</body>
</html>

laravel_ducnn/resources/views/layouts/default.blade.php
@include('layouts.head')
<body>
    <div class="container">
        <div class="row" id="header">
            <div class="col">@include('layouts.header')</div>
        </div>

        <div class="row" id="footer">
            <div class="col">@include('layouts.footer')</div>
        </div>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</html>

laravel_ducnn/resources/views/layouts/footer.blade.php
<footer>
    <h2>PHP training by LIFETIME technologies</h2>
</footer>

laravel_ducnn/resources/views/layouts/head.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>@yield('title')</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style type="text/css">
        span {
            color: red ;
        }
        #menu ul {
            list-style-type: none;
        }
        #menu li {
            color: #f1f1f1;
            display: inline-block;
            width: 150px;
            height: 40px;
            line-height: 20px;
            margin : 0px;
        }
        #menu ul {
            list-style-type: none;
            overflow: hidden;
            width: 100%;
        }
        #menu a {
            text-decoration: none;
            display: block;
        }
        #menu a:hover {
            background: white;
            color: black;
        }
        footer {
            background : black;
            color : white;
            text-align : center;
            height : 60px;
        }
        h2 {
            padding-top : 15px;
        }
    </style> 
</head>

laravel_ducnn/resources/views/layouts/header.blade.php
<br>
<header>
@can('isAdmin')
<div id="menu">
    <ul>
        <li><a href="{{ route('users.index') }}" class="btn btn-primary">List</a></li>
        <li><a href="{{ route('users.create') }}" class="btn btn-success">Add User</a></li>
    </ul>
</div>
@endcan
</header>