laravel_ducnn/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/users', 'UserController');

Auth::Routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

laravel_ducnn/resources/views/add_user.blade.php
@extends('layouts.app')
@section('title','Add user')
@section('content')
    <div class="container">
        <h1>Add a new User</h1>
        <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
            @csrf
            @include('layouts.users.form')         
        </form>
    </div>
@endsection

laravel_ducnn/resources/views/home.blade.php
@extends('layouts.app')
  
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
   
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
  
                    @can('isAdmin')
                        <div class="btn btn-success btn-lg">
                          You have Admin Access
                        </div>
                    @else
                        <div class="btn btn-info btn-lg">
                          You have User Access
                        </div>
                    @endcan
  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravel_ducnn/resources/views/list_user.blade.php
@extends('layouts.app')
@section('title','List users')
@section('content')
<form action="{{ route('users.index') }}" method="get">
    <div class="row">
        <div class="col-2">
            <input type="text" class="form-control" name="srname" placeholder="Search for Name">
        </div>
        <div class="col-2">
            <input type="text" class="form-control" name="srmail_address" placeholder="Search for Email">
        </div>
        <div class="col-2">    
            <input type="text" class="form-control" name="sraddress" placeholder="Search for Address">
        </div>
        <div class="col-2"> 
            <input type="text" class="form-control" name="srphone" placeholder="Search for Phone">
        </div>
        <div class="col-2">
            <select name="srclassroom" class="browser-default custom-select">
                @foreach($classroom as $value)
                    <option value="{{ $value->id }}">{{ $value->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-2"> 
            <input type="submit" value="Search" name="btnSearch" class="btn btn-primary">
        </div>
    </div>
</form>
<hr>
<br>
@include('flash::message')
<table class="table table-hover">
    <tr>
        <th>STT</th>
        <th>Name</th>
        <th>Class</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Create At</th>
        @can('isAdmin')
        <th>Roles</th>
        <th>Action</th>
        @endcan
    </tr>
    @foreach ( $user as $key => $value)
    <tr>
        <td>
            {{ $user->perPage() * ($user->currentPage() -1) + $key + 1}}
        </td>
        <td>
            {{ \HelperFacade::toUpperCase($value->user_name) }}
        </td>
        <td>
            {{ $value->class_name }}
        </td>
        <td>
            {{ $value->mail_address }}
        </td>
        <td>
            {{ $value->phone }}
        </td>
        <td>
            {{ $value->address }}
        </td>
        <td>
            {{ $value->user_created_at }}
        </td>
        @can('isAdmin')
        <td>
            {{ $value->role }}
        </td>
        <td>
            <button type="button" class="btn btn-default">
                <a href="{{ route('users.update', $value->id) }}">Update</a>
            </button>
        </td>
        @endcan
    </tr>
    @endforeach
    <tr>
        <td colspan="5">
            {{ $user->links() }}
        </td>
    </tr>
</table>
@endsection

laravel_ducnn/resources/views/update_user.blade.php
@extends('layouts.app')
@section('title', 'Edit User')
@section('content')
<div class="container">
    <h1>Edit User</h1>
    <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
        @include('layouts.users.form')
        {{ csrf_field() }}
        {{ method_field('PUT') }}
    </form>
</div>
@endsection

laravel_ducnn/resources/views/verify_email.blade.php
<h4>Xin chào <b>{{ $name }}</b>. Chúc mừng bạn đã đăng ký tài khoản thành công.</h4>